export const PROJECTION_FONT_OPTIONS = [
  'Noto Sans SC',
  'Noto Serif SC',
  'LXGW WenKai TC',
  'LXGW WenKai Mono TC',
  'ZCOOL XiaoWei',
  'ZCOOL QingKe HuangYou',
  'ZCOOL KuaiLe',
  'Ma Shan Zheng',
  'Long Cang',
  'Zhi Mang Xing',
  'Microsoft YaHei',
  'Microsoft JhengHei',
  'SimHei',
  'SimSun',
  'NSimSun',
  'KaiTi',
  'FangSong',
  'Arial',
  'Times New Roman',
];
