export const PREVIEW = {
  ASPECT_RATIO_16_9: '16 / 9',
  STAGE_BASE_WIDTH_PX: 1920,
  STAGE_FALLBACK_WIDTH_PX: 384,
  MIN_WIDTH_RATIO: 0.12,
  TEXT_MIN_PX: 9,
  TEXT_MAX_PX: 72,
  FALLBACK_TEXT_MAX_PX: 42,
  FALLBACK_SCALE_FLOOR: 0.85,
  FALLBACK_SCALE_MULTIPLIER: 5,
};

export const TRANSITION = {
  MIN_MS: 0,
  MAX_MS: 5000,
  DEFAULT_DELAY_MS: 20,
  DEFAULT_DURATION_MS: 60,
};

export const SCENE = {
  DEFAULT_MODE: 'normal',
  DEFAULT_SPLIT_DIRECTION: 'content_left_camera_right',
  CAMERA_PANE_MIN_PERCENT: 20,
  CAMERA_PANE_MAX_PERCENT: 40,
  CAMERA_PANE_DEFAULT_PERCENT: 30,
  CAMERA_CROP_MIN_PERCENT: 100,
  CAMERA_CROP_MAX_PERCENT: 220,
  CAMERA_CROP_DEFAULT_PERCENT: 100,
};

export const TEXT_EDITOR = {
  DEFAULT_FONT_FAMILY: 'Noto Sans SC',
  DEFAULT_COLOR: '#ffffff',
  DEFAULT_SIZE_PX: 72,
  SIZE_SMALL_PX: 48,
  SIZE_MEDIUM_PX: 72,
  SIZE_LARGE_PX: 96,
  SIZE_INPUT_MIN_PX: 24,
  SIZE_INPUT_MAX_PX: 180,
  SIZE_CLAMP_MAX_PX: 220,
  LAYOUT_DEFAULT: { xPercent: 50, yPercent: 50, scale: 1 },
  LAYOUT_X_MIN: 8,
  LAYOUT_X_MAX: 92,
  LAYOUT_Y_MIN: 10,
  LAYOUT_Y_MAX: 90,
  LAYOUT_SCALE_MIN: 0.5,
  LAYOUT_SCALE_MAX: 3.2,
};

export const TEXT_CANVAS = {
  DRAG_BOUND_MIN_PERCENT: 2,
  DRAG_BOUND_CENTER_PERCENT: 50,
  DRAG_BOUND_MAX_PERCENT: 98,
  SNAP_CENTER_PERCENT: 50,
  SNAP_THRESHOLD_PERCENT: 1.5,
  RESIZE_DIVISOR: 3,
};
