const path = require('path');

function buildIpcRegistrationOptions({
  ipcMain,
  screenManager,
  createProjectorWindow,
  forceCloseProjectorWindow,
  requestCloseControlWindow,
  getControlWindow,
  getProjectorWindow,
  appendBgDebug,
  sendToProjectorShell,
  openYouTubeWatchInProjector,
  projectorSceneState,
  getLatestProjectorContent,
  setLatestProjectorContent,
  getLatestProjectorBackground,
  setLatestProjectorBackground,
  resolveYouTubeStream,
  sanitizeMediaFileName,
  mediaYouTubeCacheDir,
  downloadService,
  ytdlpService,
  verifyLicenseToken,
  getDeviceId,
  licenseRuntime,
  trialGuard,
  readLegalDocument,
  dialog,
  resolveAbsolutePath,
  normalizeForCompare,
  isPathWithinRoot,
  mediaDir,
  mediaImagesDir,
  mediaVideosDir,
  mediaPdfDir,
  mediaPptDir,
  pptConvertTimeoutMs,
  resolveRuntimePptConvertScriptPath,
  app,
  electronDir,
  processResourcesPath,
  formatBackupStamp,
  collectReferencedMediaPathsFromQueue,
  copyDirectoryMerge,
  ndiOutputService,
}) {
  return {
    ipcMain,
    screenManager,
    createProjectorWindow,
    forceCloseProjectorWindow,
    requestCloseControlWindow,
    getControlWindow,
    getProjectorWindow,
    appendBgDebug,
    sendToProjectorShell,
    openYouTubeWatchInProjector,
    getLatestProjectorScene: projectorSceneState.getScene,
    setLatestProjectorScene: projectorSceneState.setScene,
    getLatestProjectorContent,
    setLatestProjectorContent,
    getLatestProjectorBackground,
    setLatestProjectorBackground,
    resolveYouTubeStream,
    sanitizeFileName: sanitizeMediaFileName,
    mediaYouTubeCacheDir,
    downloadUrlToFileWithRetry: downloadService.downloadUrlToFileWithRetry,
    downloadWithYtDlp: ytdlpService.downloadWithYtDlp,
    verifyLicenseToken,
    getDeviceId,
    getLicenseStatus: licenseRuntime.getCurrentLicenseStatus,
    writeAppSettings: licenseRuntime.writeSettings,
    getTrialStatus: trialGuard.getTrialStatus,
    ensureProjectionAccess: trialGuard.ensureProjectionAccess,
    readLegalDocument: (docType) => readLegalDocument(docType, path.resolve(electronDir, '..')),
    dialog,
    resolveAbsolutePath,
    normalizeForCompare,
    isPathWithinRoot,
    mediaDir,
    mediaImagesDir,
    mediaVideosDir,
    mediaPdfDir,
    mediaPptDir,
    pptConvertTimeoutMs,
    getRuntimePptConvertScriptPath: () => resolveRuntimePptConvertScriptPath({
      app,
      electronDir,
      resourcesPath: processResourcesPath,
    }),
    app,
    formatBackupStamp,
    collectReferencedMediaPathsFromQueue,
    copyDirectoryMerge,
    ndiOutputService,
  };
}

module.exports = {
  buildIpcRegistrationOptions,
};
